version: 2
updates:
  - package-ecosystem: npm
    directory: /
    exclude-paths:
      - test-fixtures/**
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
